### ISSUE TITLE
Autoscale = Reset

### ISSUE THREAD

**Issue by Saentist** [dbuezas/lovelace-plotly-graph-card#67]
Very strange situation if move graph zoom select only some lines and press Autoscale 
in 90% of cases is just same as I press Reset

Not a browser problem tested with different browsers, same effect.

**Comment by dbuezas** [comment]
I don't understand what you mean, can you show it with screenshots?

**Comment by dbuezas** [comment]
I think I understand now.
It is fixed in v1.3.7 :)

**Comment by Saentist** [comment]
It's not fixed,
select some area an when autoscale pressed is same if reset pressed.

**Comment by dbuezas** [comment]
Autoscale also scales the x axis to cover all fetched data. I assume you expect it to only autoscale the y axis of the visible data?

**Comment by Saentist** [comment]
![screentogif](https://user-images.githubusercontent.com/16975883/191007652-59d33ddc-91f1-4395-b690-b8c79187cf2a.gif)

small visualisation

**Comment by dbuezas** [comment]
Yes, that's intentional. Or rather a limitation of how data is loaded into plotly.
I guess I can add a new button to autoscale the y axis, but only for the data contained within the current range of the x axis.
